version: '3'

services:
  database:
    image: postgres:11.8-alpine
    container_name: "template-java-tech"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=java_tech_template_db
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    networks:
      - network-backend
    volumes:
      - ./srv/docker/postgresql:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d
networks:
  network-backend:
    driver: bridge